#!/bin/sh
PREFIX=config/includes.chroot
TARGET_DIR=/etc
DEST_DIR=${PREFIX}/${TARGET_DIR#/}

mkdir -pv ${DEST_DIR}
{
  echo "This ${BUILD_VARIANT} image was built $(date '+%F %R')"
  echo "Stick version $(../scripts/calc-version-number)"
  echo "Git revision $(git rev-parse HEAD)"
  echo "https://github.com/fsfw-dresden/usb-live-linux/tree/$(git rev-parse HEAD)"
  echo "(URL will show 404 not found if commit is not in main repository)"
} > ${DEST_DIR}/live-stick
