#!/bin/sh -e
lb config noauto \
    --backports=true \
        "${@}"

#        --backports true|false
#            defines if debian backports package archives should  be  included
#            in the image or not.
