#!/bin/bash

set -e

DISTRIBUTION=stretch
DESKTOP=KDE
FSFW_UNI_STICK_VERSION="$(echo "$(../tools/calc-version-number.sh)")"

lb config noauto \
    --distribution ${DISTRIBUTION} \
    --architectures amd64 \
    --archive-areas "main contrib non-free" \
    --binary-images iso-hybrid \
    --linux-packages linux-image \
    --linux-flavours "amd64" \
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}_${DESKTOP}_${DISTRIBUTION} \
    --cache-packages true \
    --source false \
    --bootloader "syslinux,grub-efi" \
    --system live \
    --updates true --backports=true --security=true \
    --parent-mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --parent-mirror-chroot http://ftp.de.debian.org/debian/ \
    --parent-mirror-chroot-security http://security.debian.org/ \
    --parent-mirror-binary http://ftp.de.debian.org/debian/ \
    --parent-mirror-binary-security http://security.debian.org/ \
    --mirror-chroot http://ftp.de.debian.org/debian/ \
    --mirror-chroot-security http://ftp.de.debian.org/debian-security/ \
    --mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --mirror-binary http://ftp.de.debian.org/debian/ \
    --mirror-binary-security http://ftp.de.debian.org/debian-security/ \
    --bootappend-live "boot=live components locales=de_DE.UTF-8 keyboard-layouts=de vga=current" \
    --bootappend-live-failsafe "boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal single" \
    --keyring-packages "debian-keyring deb-multimedia-keyring" \
    --chroot-filesystem squashfs \
    --binary-filesystem ext2 \
    --apt-source-archives false \
    --apt apt \
    --apt-indices false \
    --apt-recommends false \
    --initramfs live-boot \
    --initsystem systemd \
    --firmware-chroot false \
	"${@}"


# für minimal
#    --debootstrap-options --variant=minbase \		## funktioniert nicht
#    --apt-indices false \
#    --apt-recommends false \			
#    --firmware-chroot false \
#    --memtest none \


# Branchname im Image-Nammen setzen

nbranch=$(git branch --column)
nbranch=${nbranch////_}
nbranch=${nbranch//-/_}
nbranch=${nbranch##*"* "}
nbranch=${nbranch%% *}

if [[ ! "${nbranch}" = "master" ]]; then
lb config noauto \
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}__${nbranch}__${DESKTOP}_${DISTRIBUTION} \
	"${@}"
fi



