#!/bin/bash

INTERFACE="${1}"
STATUS="${2}"

PAC_URL="http://kjs-01.sv.dresden.de/SaferSurf/genpac.cgi"
TAG="gs-dresden"

enable_redsocks() {
        PROXY_URL=$(wget -qO - http://kjs-01.sv.dresden.de/SaferSurf/genpac.cgi|sed -nr 's/.*PROXY +([^"]*).*/\1/p'|head -n1)
        logger -t ${TAG} "configuring redsocks magic proxy to route via ${PROXY_URL}"
        [ -z ${PROXY_URL} ] && PROXY_URL="kjs-04.sv.dresden.de:3128" && logger -t ${TAG} -p user.warning "PROXY_URL not found, falling back to ${PROXY_URL}"
        PROXY_DOMAIN=${PROXY_URL%:*}
        PROXY_PORT=${PROXY_URL#*:}
        sed -ri "s/(\tip = )(.*);/\1${PROXY_DOMAIN};/" /etc/redsocks.conf
        sed -ri "s/(\tport = )(.*);/\1${PROXY_PORT};/" /etc/redsocks.conf
        logger -t ${TAG} "enabling redsocks magic proxy gateway"
        systemctl unmask redsocks
        systemctl restart redsocks
        iptables -t nat -N REDSOCKS
        iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
        iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
        iptables -t nat -A REDSOCKS -d 100.64.0.0/10 -j RETURN
        iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
        iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
        iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
        iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
        iptables -t nat -A REDSOCKS -d 198.18.0.0/15 -j RETURN
        iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
        iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN
        # local 49.gs.dresden.de subnet
        iptables -t nat -A REDSOCKS -d 10.157.0.0/16 -j RETURN
        iptables -t nat -A REDSOCKS -p tcp --dport 80 -j REDIRECT --to-ports 12345
        iptables -t nat -A REDSOCKS -p tcp -j REDIRECT --to-ports 12346
        iptables -t nat -A OUTPUT -p tcp -j REDSOCKS
}

disable_redsocks() {
        logger -t ${TAG} "disabling redsocks magic proxy gateway"
        iptables -t nat -D OUTPUT -p tcp -j REDSOCKS
        iptables -t nat -F REDSOCKS
        iptables -t nat -X REDSOCKS
        systemctl stop redsocks
        systemctl mask redsocks
}

mount_samba_share() {
        mkdir -p /media/Tausch-Schueler
        source /usr/local/.49-gs-dresden.secret
        mount -t cifs //kserver/Tausch-Schueler /media/Tausch-Schueler -o user=${user},password=${password},uid=1000,gid=1000 \
          && logger -t ${TAG} "mounted //kserver/Tausch-Schueler on /media/Tausch-Schueler"
        unset user password
}

umount_samba_share() {
        umount -vl /media/Tausch-Schueler && rmdir /media/Tausch-Schueler \
          && logger -t ${TAG} "unmounted /media/Tausch-Schueler" \
          || logger -t ${TAG} -p user.warning "WARNING: could not unmount /media/Tausch-Schueler"
}

case "${STATUS}" in
        up)
                # turn on auto-negotiation when speed is below gigabit
                [ $(ethtool ${INTERFACE} 2>&1|sed -nr 's/.*Speed: ([0-9]+)[^0-9]+$/\1/p') -lt 1000 ] && ethtool --change ${INTERFACE} autoneg on
                if [[ "${IP4_DOMAINS}" =~ ".gs.dresden.de" ]]; then
                        enable_redsocks
                        mount_samba_share
                else
                        disable_redsocks
                fi
                ;;
        down)
                disable_redsocks
                umount_samba_share
                ;;
esac
