#!/bin/bash

INFOFILE="/info.txt"

echo "Do only run this on a virtual machine and NOT on a productive system."

exit 0 # comment this if you know what you are doing




# This file contains package list which is applied directly after base installation.
# For pragmatic reasons (easy commenting, different sources) this a list of commands instead of just package names
# This script should be run with root privelidges


echo "Execution time of install script: `date`" > $INFOFILE
echo "git-branch: `git branch | head -1` " >> $INFOFILE
echo "git-commit: `git log -1 | grep -v Author` " >> $INFOFILE




# add the nominal user to the sudo group
# TODO: adapt username 'live-user'
usermod -a -G sudo live-user

# this takes effect only after restarting the shell (or `su live-user`)


# add additional package sources:

echo "
deb http://security.debian.org/ jessie/updates main contrib non-free 
deb http://http.us.debian.org/debian/ jessie main contrib 
deb-src http://http.us.debian.org/debian/ jessie main contrib 
deb http://ftp.de.debian.org/debian/ jessie main contrib non-free 
deb http://ftp.de.debian.org/debian/ jessie-updates main contrib non-free 
deb-src http://ftp.de.debian.org/debian/ jessie-updates main contrib non-free 
deb http://httpredir.debian.org/debian/ jessie-backports main contrib non-free 
# deb-src http://httpredir.debian.org/debian/ jessie-backports main contrib non-free 
deb-src http://security.debian.org/ jessie/updates main contrib non-free" > /etc/apt/sources.list


# --------- System utils ---------
apt install mc
apt install vim gvim
apt install silversearcher-ag


# --------- TeX / LaTeX / PDF handling ---------

# GUI
apt install texstudio

# Backend
apt install texlive-base
apt install texlive-bibtex-extra
apt install texlive-lang-german
apt install texlive-fonts-recommended
apt install texlive-fonts-extra
apt install texlive-latex-recommended 

# for textpos (useful in beamer-presentations)
apt install texlive-latex-extra 

# othter

# for pdfjam (pdf90)
apt install texlive-extra-utils
apt install pdftk

# to easyly write or draw into pdf documents
apt install xournal


# --------- Office ---------
apt install libreoffice


# --------- Graphic /Audio programs ---------

# Photo editing
apt install gimp

# vector graphics
apt install inkscape

# audio editing
apt install audacity


# --------- Communication ---------

apt install pidgin

apt install firefox-esr firefox-esr-l10n-de
apt install icedove
apt install enigmail


# --------- Education / science ---------


# mathematics
apt install octave octave-control

# visual function plotter
apt install kmplot



# scientific python and jupyter notebook

apt install build-essential python3-dev python3-pip
apt install numpy scipy matplotlib

pip3 ipython jupyter




# chemistry

# periodic system
apt install kalzium


# languages
apt install kwordquiz
# TODO: good vocabulary lists needed for latin, english, spanish, italian ...

