#!/bin/sh

DISTRIBUTION=buster

lb config noauto \
    --distribution ${DISTRIBUTION} \
        "${@}"

#        -d|--distribution CODENAME
#            defines the distribution of the resulting live system. This cur‐
#            rently defaults to 'buster'. The value 'sid' can be used for De‐
#            bian unstable.
