#!/bin/bash

set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_DIR=/usr/local/share/edu-materials/lego-models
DEST_DIR=${PREFIX}/${TARGET_DIR#/}

# Create target dir
mkdir -p "${DEST_DIR}"

# All models "Redistributable under CCAL version 2.0"
# https://www.ldraw.org/ldraw-org-contributor-agreement
SET_NUMS="24 36 78 79 80 86 117 166 211 223 226 310 315 324 334 338 339 423 424 465 467 573 577 658 669 710 865 869 870 872 886 910 911 912 974 1002 1091 1110 1154 1169 1196 1372 1375 1381 1383 1400 1422 1456 1463 1470 1471"
URL_BASE="https://library.ldraw.org/omr/sets"

for NUM in ${SET_NUMS}
do
  SET_URL=${URL_BASE}/${NUM}
  HTML=$(curl -sS ${SET_URL})
  TITLE=$(echo "${HTML}" | sed -nr '/title/{s/-1 / /g; s/ - / /g}; s/.*title="([0-9][^"]+)".*/\1/p' | hxunent )

  for FILE_URL in $(echo "${HTML}" | hxwls -r 2>/dev/null | grep -E '\.(mpd|ldr)$')
  do
    FILE_NAME="${TITLE}$(/bin/printf "$(echo ${FILE_URL##*/} | sed -r 's/%/\\x/g; s/[0-9 -]+//g' )")"
    echo "Retrieving ${SET_URL} => ${FILE_NAME} from ${FILE_URL}"

    FILE=$(download_file_cached "${FILE_URL}" "${FILE_NAME}") \
      && cp -a "${FILE}" "${DEST_DIR}/" \
      && echo
  done
done
