#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.utc=*|utc=*)
				LIVE_UTC="${_PARAMETER#*utc=}"
				;;
		esac
	done
}

Init ()
{
	# Checking if package is installed
	if [ ! -e /var/lib/dpkg/info/util-linux.list ] || \
	   [ -e /var/lib/live/config/util-linux ]
	then
		exit 0
	fi

	echo -n " util-linux"
}

Config ()
{
	rm -f /etc/rc?.d/*hwclock*

	if [ -n "${LIVE_UTC}" ]
	then
		LIVE_UTC="auto"
	fi

	if [ "${LIVE_UTC}" = "auto" ] && [ -x /usr/bin/os-prober ]
	then
		if os-prober|grep -qsi windows
		then
			LIVE_UTC=no
		else
			LIVE_UTC=yes
		fi

	fi

	case "${LIVE_UTC}" in
		yes)

cat > /etc/adjtime << EOF
0.0 0 0.0
0
UTC
EOF

			;;

		no)

cat > /etc/adjtime << EOF
0.0 0 0.0
0
LOCAL
EOF
                        # prevent "System clock time unset or jumped
                        # backwards, restoring from recorded timestamp"
                        # oh Lennart
                        pgrep systemd-timesyncd && SYSD=1
                        TIMEFILE=/var/lib/systemd/timesync/clock

                        [ -e $TIMEFILE ] && rm -v $TIMEFILE
                        [ "$SYSD" = "1" ] && systemctl stop systemd-timesyncd

                        # tell kernel to set the timezone and
                        # reset the system clock to local time
			hwclock --systz --localtime

                        [ "$SYSD" = "1" ] && systemctl start systemd-timesyncd
			;;
	esac

	# Creating state file
	touch /var/lib/live/config/util-linux
}

Cmdline
Init
Config
