#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --archive-areas 'main contrib non-free' \
    --parent-archive-areas 'main contrib non-free'"

#        --archive-areas ARCHIVE_AREA|"ARCHIVE_AREAS"
#            defines which package archive areas (a comma or space  separated
#            list)  of a debian package archive should be used for configured
#            debian package mirrors. By default, this is set  to  main  only.
#            Remember  to  check the licenses of each package with respect to
#            their redistributability in your juristiction when enabling con‐
#            trib or non-free with this mechanism.

#        --parent-archive-areas ARCHIVE_AREA|"ARCHIVE_AREAS"
#            defines the archive areas for derivatives of the resulting  live
#            system (a comma or space separated list).
