#!/bin/bash

set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_FILE="/usr/bin/godot4"
DEST_FILE=${PREFIX}/${TARGET_FILE#/}

ZIP_URL="https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip"

# Create target dir
mkdir -p ${PREFIX}/${TARGET_FILE%/*}

FILE=$(download_file_cached "${ZIP_URL}") \
  && unzip "${FILE}" && mv -v "$(basename --suffix=.zip "${FILE}")" "${DEST_FILE}"
