#!/bin/bash

set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_FILE="/usr/bin/godot4"
DEST_FILE=${PREFIX}/${TARGET_FILE#/}

# Create target dir
mkdir -p ${PREFIX}/${TARGET_FILE%/*}

GH_REPO=godotengine/godot
JQ_SELECTOR='select(contains("linux") and contains("x86_64") and contains("v4") and (contains("mono") | not))'

RELEASEINFO="https://api.github.com/repos/${GH_REPO}/releases"
URL=$(curl "${RELEASEINFO}" | jq -r ".[].assets[].browser_download_url | ${JQ_SELECTOR}" | head -n1)

FILE=$(download_file_cached "${URL}") \
  && unzip "${FILE}" && mv -v "$(basename --suffix=.zip "${FILE}")" "${DEST_FILE}"
