#!/bin/bash
# This script configures any environment prerequisites needed by Google Earth.
# Start Google Earth using this script rather than googleearth-bin directly.

# If you want to use an external copy of GPSBabel, you can specify it here.
# if [[ -z "$GPSBABEL" ]]; then export GPSBABEL="$(which gpsbabel)"; fi

# If DISPLAY is not set, try to autodetect a value.
if [[ -z "$DISPLAY" ]]; then
  echo "WARNING: DISPLAY environment variable is not set."
  x_displays=(/tmp/.X11-unix/X*)
  display="${x_displays[0]}"
  if [[ -e "$display" ]]; then
    export DISPLAY=":${display/*X/}"
    echo "        Found ${display}; setting DISPLAY=\"${DISPLAY}\"."
  else
    echo "        X11 display not detected; Google Earth may not run correctly."
  fi
fi

# following is a hotfix for unbreaking the search functionality
# (i18n messing with GPS coordinate separators)
# c.f. https://support.google.com/earth/thread/10088759?msgid=18922305
# still not fixed in google-earth-pro-stable 7.3.4.8248-r0 (2021-07-16)
export LC_NUMERIC=en_US.UTF-8

"$(dirname "$(readlink -f "$0")")/googleearth-bin" "$@"
