#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --debootstrap-options '--include=ca-certificates,openssl,gnupg,aptitude,gdu,eatmydata'"

#        --debootstrap-options OPTIONS
#            passes the given options to debootstrap when setting up the  base
#            system.

#        --include=alpha,beta
#               Comma  separated list of packages which will be added to down‐
#               load and extract lists.
