#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --apt-source-archives false"

#        --apt-source-archives true|false
#            defines  if  deb-src entries should be included in the resulting
#            live image's apt sources.list or not, defaults to true.
