#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --source false"

#        --source true|false
#            defines  if  a  corresponding  source  image to the binary image
#            should be built. By default this is false because most people do
#            not  require this and it involves downloading quite a few source
#            packages. However, if you distribute your live image to  others,
#            you  should make sure you build it with a source image alongside
#            to help enable you to comply with licensing terms.
