#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --updates=true"

#        --updates true|false
#            defines  if debian updates package archives should be included in
#            the image or not.

# (!) by default, enabled for all releases but unstable (sid)
# see /usr/share/live/build/functions/configuration.sh
