#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --apt-indices true"

#        --apt-indices true|false|none
#            defines if the resulting images should have apt  indices  or  not
#            and  defaults to true. If set to none, no indices are included at
#            all.
