#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --system live"

#        --system live|normal
#            defines if the resulting system image should be a live system or
#            a normal, non-live system. Defaults to live.
