#!/bin/bash

set -e

DISTRIBUTION=buster
DESKTOP=console

LIVE_HOSTNAME=fsfw-live

LIVE_LOCALES=de_DE.UTF-8,en_US.UTF-8,en_GB.UTF-8
LIVE_TIMEZONE=Europe/Berlin

LIVE_USERNAME=user
LIVE_CONFIG_NOAUTOLOGIN="false"
LIVE_CONFIG_NOROOT="false"
LIVE_USER_DEFAULT_GROUPS=audio,cdrom,dip,floppy,video,plugdev,netdev,powerdev,scanner,bluetooth,fuse,users,sudo,lpadmin,debian-tor

LIVE_KEYBOARD_MODEL=pc105
LIVE_KEYBOARD_LAYOUTS=de
LIVE_KEYBOARD_OPTIONS=""
LIVE_KEYBOARD_VARIANTS=""

LIVE_WLAN_DRIVER=""
LIVE_XORG_DRIVER=""
LIVE_CONFIG_DEBUG="true"

FSFW_UNI_STICK_VERSION="$(echo "$(../tools/calc-version-number.sh)")"

lb config noauto \
    --distribution ${DISTRIBUTION} \
    --architectures amd64 \
    --archive-areas "main contrib non-free" \
    --binary-images iso-hybrid \
    --linux-packages linux-image \
    --linux-flavours "amd64" \
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}_${DESKTOP}_${DISTRIBUTION} \
    --cache-indices false \
    --cache-packages true \
    --source false \
    --debian-installer false \
    --bootloader "syslinux,grub-efi" \
    --system live \
    --updates true --backports=true --security=true \
    --parent-mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --parent-mirror-chroot http://ftp.de.debian.org/debian/ \
    --parent-mirror-chroot-security http://security.debian.org/ \
    --parent-mirror-binary http://ftp.de.debian.org/debian/ \
    --parent-mirror-binary-security http://security.debian.org/ \
    --mirror-chroot http://ftp.de.debian.org/debian/ \
    --mirror-chroot-security http://ftp.de.debian.org/debian-security/ \
    --mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --mirror-binary http://ftp.de.debian.org/debian/ \
    --mirror-binary-security http://ftp.de.debian.org/debian-security/ \
    --debootstrap-options "--include=gnupg --variant=minbase" \
    --bootappend-live "boot=live components" \
    --bootappend-live-failsafe "boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal single" \
    --keyring-packages "debian-keyring deb-multimedia-keyring" \
    --chroot-filesystem squashfs \
    --binary-filesystem ext2 \
    --initramfs live-boot \
    --apt-source-archives false \
    --apt apt \
    --apt-indices false \
    --apt-recommends false \
    --initsystem systemd \
    --firmware-chroot false \
    --firmware-binary true \
	"${@}"

# Branchname im Image-Nammen setzen

nbranch=$(git rev-parse --abbrev-ref HEAD)		# aktuellen branch auslesen
nbranch=${nbranch////_}			# ersetze von / in _
nbranch=${nbranch//-/_}			# ersetze von - in _

if [[ ! "${nbranch}" = "master" ]]; then
lb config noauto \
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}__${nbranch}__${DESKTOP}_${DISTRIBUTION} \
	"${@}"
fi

# live config nach config/includes.chroot/etc/live/config.conf.d/system.conf  schreiben

# teste ob Verzeichnis existiert - wenn nein  --> erstellen
if [ ! -d config/includes.chroot/etc/live/config.conf.d ] ; then
    mkdir -p  config/includes.chroot/etc/live/config.conf.d
fi

# config/includes.chroot/etc/live/config.conf.d/system.conf	erstellen

for livevar in ${!LIVE_*}
    do
	if [ -n "${!livevar}" ]
	    then
		echo "${livevar}=${!livevar}" >> config/includes.chroot/etc/live/config.conf.d/system-live-config.conf
	fi
    done
