#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --cache-indices true"

#        --cache-indices true|false
#            defines if downloaded package indices and lists should be  cached
#            which  is false by default. Enabling it lets you rebuild an image
#            completely offline, however, you would not  get  updates  anymore
#            then.

