#!/bin/bash
# Download and install circuitjs electron release

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_DIR=/opt
DEST_DIR=${PREFIX}/${TARGET_DIR#/}
URL="http://falstad.com/circuit/offline/circuitjs1-linux64.tgz"
FILE=$(download_file_cached ${URL})

echo "Unpacking CircuitJS.."

# Create target dir and unpack
mkdir -p "${DEST_DIR}"

# Extract suppressing warnings about "unknown extended header keywords" LIBARCHIVE.xattr.com.apple.provenance/quarantine
tar --warning=no-unknown-keyword --exclude='._*' --directory "${DEST_DIR}" -xzf "${FILE}"

# Keep a copy of the original app invocation
cp -a ${DEST_DIR}/circuitjs1/resources/app/main.js{,.orig}

# Make Electron show with maximized window and bigger minimal font size
patch --verbose --directory=config/includes.chroot/ --strip=1 <<EOF
--- /opt/circuitjs1/resources/app/main.js.orig	2026-07-08 08:54:34.000000000 +0200
+++ /opt/circuitjs1/resources/app/main.js	2026-09-08 18:13:02.204659663 +0200
@@ -167,12 +167,16 @@
 // Create the browser window.
   var mainWindow = new BrowserWindow({width: 800,
     height: 600,
+    show: false,
     webPreferences: { nativeWindowOpen: true,
                       sandbox: false,
                       contextIsolation: false,
+                      minimumFontSize: 16,
                       preload: path.join(__dirname, 'preload.js')
     }
   })
+  mainWindow.maximize();
+  mainWindow.show();
   windows.push(mainWindow);
 
   var loadUrl = url.format({
EOF

# The sandbox being disabled in the .desktop Exec command prevents this error:
# FATAL:setuid_sandbox_host.cc The SUID sandbox helper binary was found, but
# is not configured correctly. Rather than run without sandboxing I'm aborting
# now. You need to make sure that /opt/circuitjs1/chrome-sandbox is owned by
# root and has mode 4755.

# This would be another way, left for reference.
# chown -c root config/includes.chroot/opt/circuitjs1/chrome-sandbox
# chmod -c 4755 config/includes.chroot/opt/circuitjs1/chrome-sandbox
