#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --keyring-packages 'debian-archive-keyring debian-keyring'"

#        --keyring-packages PACKAGE|"PACKAGES"
#            sets the keyring package or additional keyring packages (a space
#            separated   list).   By  default  this  is  set  to  'debian-ar‐
#            chive-keyring'.
