#!/bin/bash

INTERFACE="${1}"
STATUS="${2}"

# log network environment to memory disk
{
        env | sort
        printf "\ndefault network device: $(awk '$2 == 00000000 {print $1; exit}' /proc/net/route)\n"
        ip -4 -resolve address show
        printf '\n\n'
        ip -6 -resolve address show
} > /run/log/NetworkManager--dispatcher.${STATUS}.$(date +'%F.%H%Mh%S').log
