#!/bin/sh
. ../scripts/functions.sh
check_program_exists pandoc || exit 1

PREFIX=config/includes.chroot
TARGET_DIR=/usr/src/usb-live-linux
DEST_DIR=${PREFIX}/${TARGET_DIR#/}

mkdir -pv ${DEST_DIR}
git clone .. ${DEST_DIR}
git -C ${DEST_DIR} remote set-url origin https://github.com/fsfw-dresden/usb-live-linux
