#!/bin/bash

set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_FILE="/usr/bin/godot3"
DEST_FILE=${PREFIX}/${TARGET_FILE#/}

ZIP_URL="https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_x11.64.zip"

FILE=$(download_file_cached "${ZIP_URL}") \
  && unzip "${FILE}" && mv -v "$(basename --suffix=.zip "${FILE}")" "${DEST_FILE}"
