#!/bin/bash

set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_FILE="/usr/bin/godot3"
DEST_FILE=${PREFIX}/${TARGET_FILE#/}

ZIP_URL="https://github.com/godotengine/godot/releases/download/3.6-stable/Godot_v3.6-stable_x11.64.zip"

FILE=$(download_file_cached "${ZIP_URL}") \
  && unzip "${FILE}" && mv -v "$(basename --suffix=.zip "${FILE}")" "${DEST_FILE}"
