#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --linux-packages 'linux-image linux-headers'"

#        --linux-packages "PACKAGES"
#            sets  the  internal name of the kernel packages naming scheme. If
#            you use debian kernel packages, you will not have to  adjust  it.
#            If  you  decide  to use custom kernel packages that do not follow
#            the debian naming scheme, remember to set this option to the stub
#            of  the  packages  only  (for debian this is linux-image-2.6), so
#            that STUB-FLAVOUR results in a valid  package  name  (for  debian
#            e.g.  linux-image-686-pae).  Preferably  you use the meta package
#            name, if any, for the stub, so that your configuration is ABI in‐
#            dependent.  Also  don't  forget that you have to include stubs of
#            the binary modules packages for unionfs or aufs, and squashfs  if
#            you built them out-of-tree.
