#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_SOURCE="true"
		;;

	i386)
		_SOURCE="false"
		;;
esac

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--linux-packages "linux-image linux-headers" \
	--source "${_SOURCE}" \
"${@}"
