#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --apt-recommends false"

#        --apt-recommends true|false
#            defines  if  apt  should  install recommended packages automati‐
#            cally. By default, this is true.
