#!/bin/sh -e
lb config noauto \
    --apt-recommends false \
        "${@}"

#        --apt-recommends true|false
#            defines  if  apt  should  install recommended packages automati‐
#            cally. By default, this is true.
