#!/bin/sh

set -e

lb clean noauto "${@}"

rm -f config/binary config/bootstrap config/chroot config/common config/source config/build
rm -rf ./cache/bootstrap ./cache/contents.chroot ./config/hooks
rm -f build.log
