#!/bin/sh

set -e

lb clean noauto "${@}"

rm -f config/binary \
  config/bootstrap \
  config/chroot \
  config/common \
  config/source \
  config/build \
  config/system \
  *build.log

rm -rf cache/bootstrap
rm -rfv cache/contents.chroot \
  config/hooks \
  config/archives/* \
  config/bootloaders/* \
  config/packages*/* \
  config/includes*/* \
