{
  "netWhitelist": [
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "edge-scheme",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "www.ecosia.org",
    "wyciwyg-scheme"
  ],
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "urlhaus-1",
    "adguard-cookies",
    "adguard-popup-overlays",
    "fanboy-cookiemonster",
    "easylist-newsletters",
    "ublock-cookies-adguard",
    "DEU-0",
    "https://ublockorigin.github.io/uAssets/filters/resource-abuse.txt"
  ]
}
