#!/bin/bash
. ../scripts/functions.bash

set -ex

PREFIX=config/includes.chroot
TARGET_DIR=/usr/local/applications
DEST_DIR=${PREFIX}/${TARGET_DIR#/}

GH_REPO=ra3xdh/qucs_s
JQ_SELECTOR='contains("linux") and contains("AppImage")'

RELEASEINFO="https://api.github.com/repos/${GH_REPO}/releases"
APPIMAGE_URL=$(curl "${RELEASEINFO}" | jq -r ".[].assets[].browser_download_url | select(${JQ_SELECTOR})" | head -n1)

DOWNLOADED_FILE=$(download_file_cached "${APPIMAGE_URL}")

mkdir -pv ${DEST_DIR}
cp -val "${DOWNLOADED_FILE}" "${DEST_DIR}"
chmod -c a+x "${DEST_DIR}/${DOWNLOADED_FILE##*/}"
