#!/bin/bash
THEME_NAME="Chicago95"
ICONS_DIR="/usr/share/icons"

shopt -s nullglob

for DIR in "${ICONS_DIR}/${THEME_NAME}"/apps/*
do
        for IMG_FILE in "${DIR}/firefox."*
        do
                ln -svi ${IMG_FILE##*/} "${DIR}/firefox-esr.${IMG_FILE##*.}"
        done
done
