#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --apt-options '--yes --allow-downgrades'"

#        --apt-options OPTION|"OPTIONS"
#            defines  the default options that will be appended to every apt
#            call that is made inside chroot during the building of the  im‐
#            age.  By default, this is set to --yes to allow non-interactive
#            installation of packages.
