#!/bin/bash

set -e

DISTRIBUTION=buster
DESKTOP=Xfce
FSFW_UNI_STICK_VERSION="$(echo "$(scripts/calc-version-number.sh)")"

#    --apt-http-proxy "http://127.0.0.1:3142/" \
lb config noauto \
    --distribution ${DISTRIBUTION} \
    --architectures amd64 \
    --archive-areas "main contrib non-free" \
    --binary-images iso-hybrid \
    --linux-packages linux-image \
    --linux-flavours "amd64" \
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}_${DESKTOP}_${DISTRIBUTION} \
    --cache-packages true \
    --source false \
    --bootloader "syslinux,grub-efi" \
    --system live \
    --updates=true --backports=true --security=true \
    --parent-mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --parent-mirror-chroot http://ftp.de.debian.org/debian/ \
    --parent-mirror-chroot-security http://security.debian.org/ \
    --parent-mirror-binary http://ftp.de.debian.org/debian/ \
    --parent-mirror-binary-security http://security.debian.org/ \
    --mirror-chroot http://ftp.de.debian.org/debian/ \
    --mirror-chroot-security http://ftp.de.debian.org/debian-security/ \
    --mirror-bootstrap http://ftp.de.debian.org/debian/ \
    --mirror-binary http://ftp.de.debian.org/debian/ \
    --mirror-binary-security http://ftp.de.debian.org/debian-security/ \
    --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl,gnupg,aptitude,ncdu" \
    --bootappend-live "boot=live components locales=de_DE.UTF-8 keyboard-layouts=de timezone=Europe/Berlin vga=current net.ifnames=0 console=ttyS0" \
    --bootappend-live-failsafe "boot=live components memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal single" \
    --keyring-packages "debian-keyring deb-multimedia-keyring" \
    --chroot-filesystem squashfs \
    --binary-filesystem ext2 \
    --apt-source-archives false \
    --apt apt \
    --apt-indices true \
    --apt-recommends false \
    --initramfs live-boot \
    --initsystem systemd \
    --firmware-chroot false \
	"${@}"


# für minimal
#    --debootstrap-options --variant=minbase \		## funktioniert nicht
#    --apt-indices false \
#    --apt-recommends false \			
#    --firmware-chroot false \
#    --memtest none \


# Branchname im Image-Nammen setzen

nbranch=$(git rev-parse --abbrev-ref HEAD)		# aktuellen branch auslesen
nbranch=${nbranch////_}			# ersetze von / in _
nbranch=${nbranch//-/_}			# ersetze von - in _

if [[ ! "${nbranch}" = "master" ]]; then
lb config noauto \
    --image-name FSFW-Uni-Stick_${FSFW_UNI_STICK_VERSION}__${nbranch}__${DESKTOP}_${DISTRIBUTION} \
	"${@}"
fi



