#!/bin/bash -x
. "$(dirname $(realpath "${0}"))/functions.sh"
. "$(dirname $(realpath "${0}"))/functions.bash"
cd_repo_root

# give some rudimentary help if requested
case "${1}" in
    "-h")
        ;&
    "--help")
        print_info "usage is ${0} [ISO [TARGETDIRECTORY [TOTALSIZEMB* [FATPARTITIONSIZEMB**]]]]"
        print_info "   (*) defaults to $((10 * 2**10))"
        print_info "  (**) defaults to 1450"
        exit
        ;;
esac

select_live_iso_for_image() {
    OPTIONS=()
    cd iso-images
    for ISO in $(command ls -Lt *.iso)
    do
        #ISO=${ISO##iso-images}
        SIZESTR=$(numfmt --to=iec-i --suffix B $(stat --dereference --format='%s' "${ISO}"))
        OPTIONS+=(${ISO} "${SIZESTR} $(date --date=@$(stat --dereference --format='%Y' "${ISO}") "+%F %_H:%M:%S")")
    done
    TEXT="Please choose the live system ISO the image should be created for."
    TITLE="SELECT LIVE SYSTEM ISO"
    display_menu "${TITLE}" "${TEXT}" "${OPTIONS[@]}"
}

# crudely map build variant or iso names to FSFW stick type
map_image_name_to_stick_type() {
    # match patterns in a case-insensitive fashion
    shopt -s nocasematch

    # limited amount of variants => stupid substring match
    case ${@} in
        *schul*)
            echo "SCHULSTICK"
            ;;
        *uni*)
            echo "UNISTICK"
            ;;
        *lern*)
            echo "LERNSTICK"
            ;;
        *mini*)
            echo "MINISTICK"
            ;;
        *)
            echo "couldn't detect variant from string ${@}"
            exit 1
            ;;
    esac
}

# ISO can be given as first parameter
[ -n "${1}" ] && ISO=$1 || ISO="iso-images/$(select_live_iso_for_image)"

# try to detect stick type from image name
FAT_LABEL="$(map_image_name_to_stick_type ${ISO})" || FAT_LABEL="LIVESTICK"

# cut off file ending of ISO and replace with .img
IMG=${ISO##*/}
IMG=${IMG%%.iso}
IMG=${IMG%%.hybrid}.img

# target directory for image file as second parameter
[ -n "${2}" ] && IMG=$2/${IMG}

# total size of image in MiB as 4th parameter
[ -n "${3}" ] && size_mb_disk_image=$3 || size_mb_disk_image=$((10 * 2**10))

# size of boot / data exchange FAT32 partition in MiB as 5th parameter
[ -n "${4}" ] && size_mb_partition_fat32=$4 || size_mb_partition_fat32=1450

# create image file
truncate --size=${size_mb_disk_image}M ${IMG}

# connect image to loop device
LOOP=$(losetup --partscan --verbose --show --find ${IMG})

# install ISO onto it
HOTFIX="none" scripts/stick-install ${LOOP} ${ISO} ${FAT_LABEL} ${size_mb_partition_fat32}

# free loop device
losetup --verbose --detach ${LOOP}
