#!/bin/sh

. "$(dirname $(realpath "${0}"))/functions.sh"
cd_repo_root

check_program_exists systemd-nspawn
check_program_exists debootstrap

DEPS="
systemd-container
grub-pc-bin
grub-efi-ia32-bin
shim-signed
syslinux-common
parted
fatattr
dosfstools
f2fs-tools
libcdio-utils
dialog
ccze
live-build
git
rsync
wget
curl
gallery-dl
youtube-dl
ca-certificates
unzip
bash
jq
patch
pandoc
make
tig
ranger
qemu-utils libnbd-bin nbdkit
bash-completion
pipemeter
nocache
pigz
"

# If no container directory exists, initiate a debian testing install with all our dependencies
if [ ! -d build/container ]
then
  printf "${COLOR_CYAN}Initializing a debian testing container for building..${COLOR_OFF}\n"
  printf " (this will take a few minutes)\n"
  printf "echo 'systemd-container is being used to automatically remove /proc and /sys mounts after this shell process has terminated. The container is being run with ${COLOR_CYAN}full root access to the host system${COLOR_OFF} at the moment (pull requests welcome for constraining that without breakage).'\n"
  printf "\n"
  printf "\n"
  debootstrap --verbose --cache-dir=${PWD}/build/cache/packages.bootstrap --include=$(echo ${DEPS}|tr ' ' ',') testing build/container http://ftp.debian.org/debian
  {
    echo "cd /mnt/usb-live-linux/"
    echo "clear"
    printf "echo '${COLOR_CYAN}You have entered a debian container environment with the required tool set to build the usb-live-linux project.${COLOR_OFF}'\n"
    printf "echo ''\n"
    echo "echo"
    printf "echo 'run ${COLOR_CYAN}scripts/build-live-iso${COLOR_OFF} to build ISO-image'\n"
    printf "echo ' or ${COLOR_CYAN}scripts/stick-install${COLOR_OFF} to install a finished ISO-image onto a flash drive or into an image file'\n"
  } >> build/container/root/.bashrc
fi

# Update apt database
systemd-nspawn --directory=build/container apt update

# Apply added dependencies
systemd-nspawn --directory=build/container apt install --no-install-recommends --no-upgrade ${DEPS}

# Now bind-mount this repository and enter the container (without any device access restrictions)
systemd-nspawn --directory=build/container --bind=${PWD}:/mnt/usb-live-linux --bind=/dev --property='DeviceAllow=block-* rwm' --property='DeviceAllow=char-* rwm' --console=pipe

# vim: ts=2 sw=2
