#!/bin/bash
set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
TARGET_DIR="/usr/local/bin"
DEST_DIR=${PREFIX}/${TARGET_DIR#/}

# Create target dir
mkdir -p "${DEST_DIR}"

GH_REPO=containers/podman-tui
JQ_SELECTOR='select(contains("linux_amd64"))'

RELEASEINFO="https://api.github.com/repos/${GH_REPO}/releases"
URL=$(curl "${RELEASEINFO}" | jq -r ".[].assets[].browser_download_url | ${JQ_SELECTOR}" | head -n1)

FILE=$(download_file_cached ${URL}) \
  && unzip -jd "${DEST_DIR}" "${FILE}"
