#!/bin/sh
# generate a machine-dependent hostname

try_read() {
  for ATTR in $@
  do
    ATTRPATH=${SYSBASE}/${ATTR}
    [ -f ${ATTRPATH} ] && cat ${ATTRPATH} && return
  done
}

SYSBASE="/sys/class/dmi/id"

SERIAL=$(try_read product_uuid chassis_serial product_serial board_serial)
VENDOR=$(try_read sys_vendor chassis_vendor)

# fall back to boot (/proc creation) time to generate unique VM hostnames
[ -z ${SERIAL} ] && SERIAL=$(stat -c %Z /proc)

# unlikely to not be set but might happen
[ -z ${VENDOR} ] && VENDOR="UNKNOWN"

# calculate a 5-char hex ID
ID=$(echo ${SERIAL}|sha256sum|cut -c 1-5)

# put the hostname in place
echo "machine-$(echo ${VENDOR}|cut -c 1-4)-${ID}" > /etc/hostname

# make subsequent 0020-hostname pick up the new name
[ -e /var/lib/live/config/hostname ] && rm /var/lib/live/config/hostname
