#!/bin/sh

DISTRIBUTION=trixie

LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --distribution ${DISTRIBUTION}"

#        -d|--distribution CODENAME
#            defines the distribution of the resulting live system. This cur‐
#            rently defaults to '…'. The value 'sid' can be used for De‐
#            bian unstable.
