# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1477943686);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1477943806);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1477943326);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 1477944046);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1477943566);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1477943446);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1477943926);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 184320);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1477946110869");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1477947891869");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1477943201992");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1477946801992");
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160921204512");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20160921204512");
user_pref("browser.startup.homepage_override.mstone", "45.4.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1478029596744");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1477943217417");
user_pref("datareporting.policy.firstRunTime", "1477943196744");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 2756);
user_pref("datareporting.sessions.current.main", 45);
user_pref("datareporting.sessions.current.sessionRestored", 2382);
user_pref("datareporting.sessions.current.startTime", "1477946099901");
user_pref("datareporting.sessions.current.totalTime", 29);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.1", "{\"s\":1477943205058,\"a\":25,\"t\":1695,\"c\":true,\"m\":84,\"fp\":2693,\"sr\":2364}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1477944901165,\"a\":15,\"t\":81,\"c\":true,\"m\":63,\"fp\":2056,\"sr\":2089}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1477945080756,\"a\":1,\"t\":7,\"c\":true,\"m\":67,\"fp\":2490,\"sr\":2161}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-de@firefox-esr.mozilla.org\":{\"version\":\"45.4.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox-esr/browser/extensions/langpack-de@firefox-esr.mozilla.org.xpi\",\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.4.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1477943687);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.4.0");
user_pref("extensions.lastPlatformVersion", "45.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1474526330000}},\"app-global\":{\"langpack-de@firefox-esr.mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/langpack-de@firefox-esr.mozilla.org.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1474525921000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.4.0\",\"st\":1474526330000}}}");
user_pref("gecko.buildID", "20160921204512");
user_pref("gecko.mstone", "45.4.0");
user_pref("idle.lastDailyNotification", 1477943425);
user_pref("media.gmp-manager.buildID", "20160921204512");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1477943425);
user_pref("places.history.expiration.transient_current_max_pages", 6157);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1477943425);
user_pref("toolkit.startup.last_success", 1477946099);
user_pref("toolkit.telemetry.cachedClientID", "ae22e065-71a9-4c6e-851b-42982df1030d");
user_pref("toolkit.telemetry.previousBuildID", "20160921204512");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.key.menuAccessKeyFocuses", false);
