#!/bin/bash

. ../scripts/functions.bash

check_dependencies qemu-utils libnbd-bin nbdkit

PREFIX=config/includes.chroot
TARGET_DIR=/usr/local/games/
DEST_DIR=${PREFIX}/${TARGET_DIR#/}

URL="https://download2044.mediafire.com/vzx6uswbhrag/vzinn93fyydb479/Windows+95+Hard+Disk.vhd"
FILENAME="windows95.vhd"

mkdir -pv ${DEST_DIR}
FILE=$(download_file_cached ${URL} ${FILENAME})
cp -v ${FILE} ${DEST_DIR}

# fix vfbackup error.. and don't fail if this doesn't work
[ -e /dev/loop-control ] && {
    TMPDIR=$(mktemp -d /tmp/stick.XXXXXX)
    MNTDIR=${TMPDIR}/mount
    PARTDIR=${TMPDIR}/partition
    VFAT=${PARTDIR}/vfat
    SOCKET=${TMPDIR}/qemu-nbd.sock
    TARGET="AUTOEXEC.BAT"

    echo "rewriting ${TARGET}, just a second.."
    trap "rmdir ${MNTDIR} ${PARTDIR} ${TMPDIR}" EXIT SIGHUP SIGQUIT SIGTERM

    mkdir -p ${PARTDIR} ${MNTDIR}

    qemu-nbd --socket=${SOCKET} "${DEST_DIR}/${FILENAME}" &
    nbdfuse ${VFAT} --command nbdkit --stdin nbd socket=${SOCKET} --filter=partition partition=1 &
    sleep 1
    mount -o loop ${VFAT} ${MNTDIR} && \
      echo smartdrv >> ${MNTDIR}/${TARGET}
    umount --detach-loop ${MNTDIR}
    sleep 1
    umount ${PARTDIR}
} || true
