#!/bin/bash

# "As bazel has not yet been packaged for
# Debian, there is no possibility of packaging a more recent version of
# anki, so I am reluctantly marking this upgrade request as "serious" to
# keep anki out of testing for the time being.  It is unlikely to make
# it into bookworm."
# "If you wish to use an up-to-date version of Anki in the meantime,
# please feel free to download it from upstream; they provide a
# pre-packaged pre-compiled version."
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=958853
set -e

. ../scripts/functions.bash

PREFIX=config/includes.chroot
DEST_DIR=${PREFIX}/tmp

mkdir -pv ${DEST_DIR}

URL="https://github.com/ankitects/anki/releases/download/23.10.1/anki-23.10.1-linux-qt6.tar.zst"
FILE=$(download_file_cached ${URL}) \
  && tar --extract --file "${FILE}" --directory "${DEST_DIR}" --zstd
