#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --backports=true"

#        --backports true|false
#            defines if debian backports package archives should  be  included
#            in the image or not.

# (!) Backports repositories are only available for stable releases.
