#!/bin/sh -e
LB_CONFIG_PARAMETERS="${LB_CONFIG_PARAMETERS} \
    --zsync false"

#        --zsync true|false
#            defines whether a file for distributing the  image  in  zsync(1)
#            format will be generated. Defaults to true.
